spring.application.name=train-service
server.port=8081
#PostgreSQL connection
#Train_DB
spring.datasource.train.url=jdbc:postgresql://localhost:5432/train_service
spring.datasource.train.username=${DB_USERNAME}
spring.datasource.train.password=${DB_PASSWORD}
spring.datasource.train.driver-class-name=org.postgresql.Driver




#User_DB
spring.datasource.user.url=jdbc:postgresql://localhost:5432/userservice
spring.datasource.user.username=${DB_USERNAME}
spring.datasource.user.password=${DB_PASSWORD}
spring.datasource.user.driver-class-name=org.postgresql.Driver



#JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=268549
server.ssl.key-alias=springboot
#Liquibase changelog file
#user.liquibase.change-log=classpath:db/changelog/user_changelog.xml
#train.liquibase.change-log=classpath:db/changelog/traindb_changelog.xml
