spring.application.name=train-service
server.port=8081
#PostgreSQL connection
#Train_DB
spring.datasource.train.url=jdbc:postgresql://localhost:5432/train_service
spring.datasource.train.username=postgres
spring.datasource.train.password=Utt@m3103
spring.datasource.train.driver-class-name=org.postgresql.Driver




#User_DB
spring.datasource.user.url=jdbc:postgresql://localhost:5432/userservice
spring.datasource.user.username=postgres
spring.datasource.user.password=Utt@m3103
spring.datasource.user.driver-class-name=org.postgresql.Driver



#JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.propeerties.hibernate.format_sql=true

#Liquibase changelog file
#user.liquibase.change-log=classpath:db/changelog/user_changelog.xml
#train.liquibase.change-log=classpath:db/changelog/traindb_changelog.xml

# Spring Security OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=962290523263-g37l0r07ra8aa0jj7jea01s6k3vfge29.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# OAuth2 Provider Configuration (optional but recommended)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email


